# This file was generated by GoReleaser. DO NOT EDIT.
class Tusk < Formula
  desc "The modern task runner"
  homepage "https://github.com/rliebz/tusk"
  version "0.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rliebz/tusk/releases/download/v0.6.0/tusk_0.6.0_darwin_amd64.tar.gz"
    sha256 "fb8c5bc5dba66856276cb97b9b20472ebaea088f743ce927f8a0d9515079dd72"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rliebz/tusk/releases/download/v0.6.0/tusk_0.6.0_linux_amd64.tar.gz"
      sha256 "85bc4c53e85a8b0a3c9ed59bd311fdf845eece4c8e493daee797cc255a751ded"
    end
  end

  def install
    bin.install "tusk"
    
    bash_completion.install "completion/tusk-completion.bash"
    zsh_completion.install "completion/_tusk"
  end

  test do
    system "#{bin}/tusk --version"
  end
end
