# This file was generated by GoReleaser. DO NOT EDIT.
class Tusk < Formula
  desc "The modern task runner"
  homepage "https://github.com/rliebz/tusk"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rliebz/tusk/releases/download/v0.6.1/tusk_0.6.1_darwin_amd64.tar.gz"
    sha256 "1be9d16f072bcc3c8b48131de106a492297a7ab3f67ae2c3c3b1f9c0e2a60065"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rliebz/tusk/releases/download/v0.6.1/tusk_0.6.1_linux_amd64.tar.gz"
      sha256 "5554abb54f820b64426440dce386a841d1b4dde591e173f659196fb91cf54bdb"
    end
  end

  def install
    bin.install "tusk"
    
    bash_completion.install "completion/tusk-completion.bash"
    zsh_completion.install "completion/_tusk"
  end

  test do
    system "#{bin}/tusk --version"
  end
end
