# This file was generated by GoReleaser. DO NOT EDIT.
class Tusk < Formula
  desc "The modern task runner"
  homepage "https://github.com/rliebz/tusk"
  version "0.4.7"

  if OS.mac?
    url "https://github.com/rliebz/tusk/releases/download/v0.4.7/tusk_0.4.7_darwin_amd64.tar.gz"
    sha256 "a72a54ffef26d9ec11e294883926793b6a9716067c7d8f567fc747ceee7f646c"
  elsif OS.linux?
    url "https://github.com/rliebz/tusk/releases/download/v0.4.7/tusk_0.4.7_linux_amd64.tar.gz"
    sha256 "4c764392d753d53301cf3fcc0685eb7cd25a2bd69e98bef855c9b613b2a5dac6"
  end

  def install
    bin.install "tusk"
    
    bash_completion.install "completion/tusk-completion.bash"
    zsh_completion.install "completion/_tusk"
  end

  test do
    system "#{bin}/tusk --version"
  end
end
